import { ArrowRight, Car, Hammer, Headphones, Home, Leaf, MapPin, MessageCircle, Paintbrush, Search, Snowflake, Wrench, Zap } from "lucide-react";
import { MobileMenu } from "./components/mobile-menu";
import { siteConfig } from "../lib/site-config";

const categories = [
  { name: "Hogar", icon: Home, category: "home" }, { name: "Climatización", icon: Snowflake, category: "climate" },
  { name: "Automotor", icon: Car, category: "auto" }, { name: "Construcción", icon: Hammer, category: "construction" },
  { name: "Jardín", icon: Leaf, category: "garden" }, { name: "Limpieza", icon: Wrench, category: "cleaning" },
  { name: "Seguridad", icon: Wrench, category: "security" }, { name: "Tecnología", icon: Wrench, category: "technology" },
];
const quickLinks = ["Electricidad", "Aire acondicionado", "Automotor", "Jardinería", "Reparaciones"];
const featuredServices = [
  { title: "Electricidad automotriz", text: "Diagnóstico y soluciones eléctricas para vehículos.", type: "Atención rápida", image: "https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=1200&q=82", position: "center", slug: "electricidad-automotriz" },
  { title: "Aire acondicionado", text: "Instalación, revisión y mantenimiento del equipo.", type: "Servicio destacado", image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=82", position: "center", slug: "instalacion-aire-acondicionado" },
  { title: "Jardinería y mantenimiento", text: "Evaluamos el trabajo y preparamos la cotización.", type: "Con evaluación", image: "https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=1200&q=82", position: "center", slug: "jardineria" },
];
const compactServices = [
  { title: "Electricidad para el hogar", text: "Instalaciones · fallas · mantenimiento", type: "Atención rápida", icon: Zap, slug: "electricidad" },
  { title: "Reparaciones generales", text: "Arreglos y mantenimiento cotidiano", type: "Atención rápida", icon: Wrench, slug: "reparaciones-generales" },
  { title: "Chapería y pintura", text: "Evaluación y cotización según el trabajo", type: "Con evaluación", icon: Paintbrush, slug: "chaperia" },
];
const focus = "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-500";
const Logo = () => <span className="flex items-center gap-2.5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-brand-500 text-white"><Wrench size={18} strokeWidth={2} /></span><span className="whitespace-nowrap text-[15px] font-semibold tracking-[-.03em] min-[390px]:text-base sm:text-lg">TODOSERVICIOS <span className="text-brand-400">PY</span></span></span>;

export default function HomePage() {
  return <main className="min-h-screen bg-soft pb-20 sm:pb-0">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-ink text-white"><div className="container-shell flex h-16 items-center justify-between gap-3 sm:h-[68px]"><a href="#inicio" aria-label={`${siteConfig.brandName} - Inicio`} className={focus}><Logo /></a><nav className="hidden items-center gap-7 text-[13px] text-white/75 lg:flex" aria-label="Navegación principal"><a className={`transition hover:text-white ${focus}`} href="/servicios">Servicios</a><a className={`transition hover:text-white ${focus}`} href="#destacados">Destacados</a><a className={`transition hover:text-white ${focus}`} href="#como-funciona">Cómo funciona</a><a className={`transition hover:text-white ${focus}`} href="#prestadores">Prestadores</a></nav><div className="hidden items-center gap-3 sm:flex"><a href="/servicios" className={`px-3 py-2 text-[13px] text-white/75 transition hover:text-white ${focus}`}>Ver servicios</a><a href="#solicitud" className={`rounded-lg bg-brand-500 px-5 py-2.5 text-[13px] font-semibold text-white transition hover:bg-brand-600 ${focus}`}>Solicitar atención</a></div><MobileMenu /></div></header>

    <section id="inicio" className="border-b border-white/10 bg-ink text-white"><div className="container-shell grid gap-6 py-7 sm:py-9 lg:grid-cols-[1.2fr_.8fr] lg:items-stretch lg:gap-8 lg:py-10"><div className="min-w-0"><div className="mb-3 flex items-center gap-2 text-[12px] text-white/70"><Headphones size={15} className="text-brand-400" /> Central integral de servicios</div><h1 className="max-w-3xl text-[32px] font-normal leading-[1.08] tracking-[-.04em] min-[390px]:text-[35px] sm:text-[46px] lg:text-[50px]">Todos los servicios que necesitás, <span className="text-brand-400">en un solo lugar.</span></h1><p className="mt-3 max-w-2xl text-[14px] leading-6 text-white/75 sm:text-[15px]">Contanos qué necesitás. Atendemos, evaluamos, cotizamos y coordinamos la solución.</p>
    <form id="solicitud" action="#atencion-central" className="mt-5 grid gap-2 rounded-xl bg-white p-2 text-ink sm:grid-cols-[1fr_190px_auto]"><label className="flex min-h-[52px] items-center gap-3 rounded-lg px-3"><span className="sr-only">¿Qué necesitás resolver?</span><Search size={18} className="shrink-0 text-muted" /><input name="necesidad" placeholder="¿Qué necesitás resolver?" className={`min-w-0 flex-1 bg-transparent text-[14px] outline-none placeholder:text-muted ${focus}`} /></label><label className="flex min-h-[52px] items-center gap-2 rounded-lg border border-border px-3 sm:rounded-none sm:border-y-0 sm:border-r-0 sm:border-l"><span className="sr-only">Tu ciudad o ubicación</span><MapPin size={17} className="shrink-0 text-brand-600" /><select name="zona" defaultValue="" className={`w-full bg-transparent text-[14px] outline-none ${focus}`}><option value="" disabled>Tu ubicación</option><option>Asunción</option><option>Central</option><option>San Lorenzo</option><option>Luque</option><option>Otra ciudad</option></select></label><button type="submit" className={`min-h-[52px] rounded-lg bg-brand-500 px-6 text-[14px] font-semibold text-white transition hover:bg-brand-600 active:scale-[.99] ${focus}`}>Solicitar atención</button></form>
    <div className="mt-5"><p className="mb-2.5 text-[12px] font-medium text-white/60">Accesos rápidos</p><div className="flex flex-wrap gap-2">{quickLinks.map(name => <a key={name} href={`/#solicitud?servicio=${encodeURIComponent(name)}`} className={`min-h-10 rounded-full border border-white/25 bg-white/[.09] px-3.5 py-2.5 text-[13px] text-white/90 transition hover:border-white/50 hover:bg-white/[.14] ${focus}`}>{name}</a>)}<a href="/servicios" className={`min-h-10 rounded-full border border-brand-400/70 px-3.5 py-2.5 text-[13px] font-medium text-brand-400 transition hover:bg-brand-500 hover:text-white ${focus}`}>Más servicios</a></div></div></div>
    <aside className="hidden lg:grid lg:grid-rows-[1fr_auto] lg:gap-3"><div className="relative min-h-[250px] overflow-hidden rounded-xl border border-white/10 bg-white/5"><img src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1000&q=82" alt="Profesional realizando un trabajo de servicio" width="1000" height="750" fetchPriority="high" className="h-full w-full object-cover object-center" /><div className="absolute inset-x-0 bottom-0 bg-black/55 px-5 py-4"><p className="mb-0 text-[13px] text-white/90">Una sola atención para distintas necesidades.</p></div></div><a href="#atencion-central" className={`flex min-h-[74px] items-center justify-between rounded-xl bg-white p-4 text-ink transition hover:bg-[#f8fafc] ${focus}`}><span className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-brand-50 text-brand-600"><MessageCircle size={19} /></span><span><strong className="block text-[14px] font-semibold">Atención central</strong><span className="text-[13px] text-muted">Un número. Una atención. Todos los servicios.</span></span></span><ArrowRight size={17} /></a></aside></div></section>

    <section className="py-5 sm:py-6"><div className="container-shell grid gap-3 md:grid-cols-2"><a href="#solicitud" className={`flex min-h-[132px] flex-col justify-between rounded-xl bg-white p-5 ring-1 ring-border transition hover:ring-ink/20 sm:p-6 ${focus}`}><div><p className="mb-1.5 text-[12px] font-medium text-ink">Necesito ayuda ahora</p><h2 className="text-[21px] font-normal tracking-tight sm:text-[23px]">¿Necesitás resolver algo hoy?</h2><p className="mt-1.5 text-[14px] leading-5 text-muted">Contanos el problema y gestionamos la atención.</p></div><span className="mt-4 inline-flex items-center gap-2 text-[13px] font-semibold">Solicitar atención <ArrowRight size={16} /></span></a><a href="#solicitud" className={`flex min-h-[132px] flex-col justify-between rounded-xl bg-brand-50 p-5 ring-1 ring-brand-100 transition hover:ring-brand-400 sm:p-6 ${focus}`}><div><p className="mb-1.5 text-[12px] font-medium text-brand-600">Trabajo con evaluación</p><h2 className="text-[21px] font-normal tracking-tight sm:text-[23px]">¿Necesitás cotizar un trabajo?</h2><p className="mt-1.5 text-[14px] leading-5 text-muted">Describí lo que necesitás y preparamos la evaluación.</p></div><span className="mt-4 inline-flex items-center gap-2 text-[13px] font-semibold text-brand-600">Pedir cotización <ArrowRight size={16} /></span></a></div></section>

    <section id="categorias" className="scroll-mt-20 pb-7 sm:pb-9"><div className="container-shell"><div className="mb-4 flex items-end justify-between gap-4"><div><p className="mb-1 text-[12px] font-medium text-brand-600">Explorar servicios</p><h2 className="text-[24px] font-normal tracking-[-.025em] sm:text-[28px]">Encontrá la solución que necesitás</h2><p className="mt-1.5 text-[14px] text-muted">Explorá las principales categorías o mirá el catálogo completo.</p></div><a href="/servicios" className={`hidden text-[13px] font-semibold text-brand-600 sm:block ${focus}`}>Ver todos →</a></div><div className="grid grid-cols-2 gap-2.5 sm:grid-cols-4 lg:grid-cols-8">{categories.map(({ name, icon: Icon, category }) => <a key={name} href={`/servicios?categoria=${category}`} className={`group flex min-h-[92px] items-center gap-3 rounded-lg bg-white p-3 ring-1 ring-border transition hover:bg-[#eff6ff] hover:ring-ink/30 sm:flex-col sm:justify-center sm:text-center ${focus}`}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#eff6ff] text-ink"><Icon size={19} /></span><span className="text-[13px] font-medium leading-tight">{name}</span></a>)}</div><a href="/servicios" className={`mt-3 flex min-h-11 items-center justify-center rounded-lg border border-border bg-white text-[13px] font-semibold text-brand-600 sm:hidden ${focus}`}>Ver todos los servicios <ArrowRight size={15} className="ml-2" /></a></div></section>

    <section id="destacados" className="scroll-mt-20 border-y border-border bg-white py-8 sm:py-10"><div className="container-shell"><div className="mb-5 flex items-end justify-between gap-5"><div><p className="mb-1 text-[12px] font-medium text-brand-600">Servicios destacados</p><h2 className="text-[24px] font-normal tracking-[-.025em] sm:text-[28px]">Necesidades frecuentes, atención más directa</h2></div><a href="/servicios" className={`hidden text-[13px] font-medium text-brand-600 sm:block ${focus}`}>Explorar todos →</a></div><div className="grid gap-3 md:grid-cols-3">{featuredServices.map(service => <a key={service.title} href={`/?servicio=${service.slug}#solicitud`} className={`group overflow-hidden rounded-xl bg-white ring-1 ring-border transition hover:ring-ink/25 ${focus}`}><div className="aspect-[4/3] overflow-hidden bg-soft"><img loading="lazy" width="900" height="675" src={service.image} alt={`${service.title} - fotografía temporal de desarrollo`} className="h-full w-full object-cover transition duration-200 group-hover:scale-[1.015]" style={{ objectPosition: service.position }} /></div><div className="p-4"><span className="text-[11px] font-medium text-brand-600">{service.type}</span><h3 className="mt-1.5 text-[17px] font-semibold">{service.title}</h3><p className="mt-1.5 text-[14px] leading-5 text-muted">{service.text}</p><span className="mt-4 inline-flex items-center gap-1.5 text-[13px] font-semibold text-brand-600">Solicitar <ArrowRight size={15} /></span></div></a>)}</div><div className="mt-4 grid gap-2.5 md:grid-cols-3">{compactServices.map(({ title, text, type, icon: Icon, slug }) => <a key={title} href={`/?servicio=${slug}#solicitud`} className={`group grid grid-cols-[48px_1fr_auto] items-center gap-3 rounded-lg bg-white p-3.5 ring-1 ring-border transition hover:ring-ink/30 ${focus}`}><span className="grid h-12 w-12 place-items-center rounded-lg bg-[#eff6ff] text-ink"><Icon size={21} /></span><span className="min-w-0"><span className="block text-[11px] font-medium text-brand-600">{type}</span><strong className="mt-0.5 block text-[14px] font-semibold">{title}</strong><span className="mt-0.5 block text-[13px] text-muted">{text}</span></span><ArrowRight size={17} className="text-muted" /></a>)}</div></div></section>

    <section id="como-funciona" className="scroll-mt-20 py-6 sm:py-7"><div className="container-shell grid gap-4 lg:grid-cols-[.55fr_1.45fr] lg:items-center lg:gap-6"><div><p className="mb-1 text-[12px] font-medium text-brand-600">Cómo funciona</p><h2 className="text-[24px] font-normal sm:text-[27px]">Así de simple.</h2></div><div className="grid overflow-hidden rounded-xl bg-white ring-1 ring-border sm:grid-cols-3">{[["01","Contanos qué necesitás"],["02","Recibí atención y cotización"],["03","Coordinamos el servicio"]].map(([number,title]) => <div key={number} className="flex min-h-[62px] items-center gap-3 border-b border-border px-4 py-3 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-brand-50 text-[11px] font-semibold text-brand-600">{number}</span><h3 className="text-[13px] font-semibold sm:text-[14px]">{title}</h3></div>)}</div></div></section>
    <section id="atencion-central" className="scroll-mt-20 pb-4 sm:pb-5"><div className="container-shell"><div className="flex flex-col gap-5 rounded-xl bg-ink p-5 text-white sm:p-6 lg:flex-row lg:items-center lg:justify-between lg:px-7"><div><div className="flex items-center gap-2 text-[11px] font-medium uppercase text-brand-400"><Headphones size={15} /> Atención central {siteConfig.brandName}</div><h2 className="mt-2 text-[25px] font-normal sm:text-[29px]">Un número. Una atención. <span className="text-brand-400">Todos los servicios.</span></h2><p className="mt-2 max-w-2xl text-[14px] text-white/75">Centralizamos la atención, cotización y coordinación de tus servicios desde un solo lugar.</p></div><a href="#solicitud" className={`inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-brand-500 px-5 text-[14px] font-semibold text-white transition hover:bg-brand-600 lg:w-auto ${focus}`}>Solicitar atención <ArrowRight size={16} /></a></div></div></section>
    <section id="prestadores" className="scroll-mt-20 pb-4 sm:pb-5"><div className="container-shell"><div className="flex flex-col gap-4 rounded-xl bg-white p-5 ring-1 ring-border sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p className="mb-1 text-[11px] font-medium uppercase text-ink">Red de prestadores</p><h2 className="text-[20px] font-normal sm:text-[22px]">¿Sos profesional o tenés una empresa de servicios?</h2><p className="mt-1 text-[14px] text-muted">Formá parte de nuestra red de prestadores.</p></div><a href="#atencion-central" className={`inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-ink px-5 text-[13px] font-medium text-white sm:w-auto ${focus}`}>Quiero trabajar con {siteConfig.brandName} <ArrowRight size={15} /></a></div></div></section>
    <footer className="border-t border-border bg-white py-5 sm:py-6"><div className="container-shell grid gap-5 sm:grid-cols-[1.4fr_1fr_1fr]"><div><a href="#inicio" className={focus}><Logo /></a><p className="mt-2.5 text-[13px] text-muted">Central integral de servicios para Paraguay.</p><p className="mt-1.5 text-[12px] text-muted">© 2026 {siteConfig.brandName}</p></div><div><p className="mb-2 text-[12px] font-semibold">Navegación</p><div className="flex flex-col gap-1.5 text-[13px] text-muted"><a href="/servicios">Servicios</a><a href="#destacados">Destacados</a><a href="#como-funciona">Cómo funciona</a><a href="#prestadores">Prestadores</a></div></div><div><p className="mb-2 text-[12px] font-semibold">Atención</p><p className="text-[13px] leading-5 text-muted">Un solo contacto para evaluación, cotización y coordinación.</p></div></div></footer>
    <a href="#solicitud" className={`fixed left-3 right-3 z-40 flex min-h-12 items-center justify-center gap-2 rounded-full bg-brand-500 px-5 text-[13px] font-semibold text-white shadow-[0_8px_22px_rgba(15,42,67,.2)] [bottom:calc(.75rem+env(safe-area-inset-bottom))] sm:hidden ${focus}`}>Solicitar atención <ArrowRight size={16} /></a>
  </main>;
}
