import { ArrowRight, BadgeCheck, Car, ClipboardCheck, Hammer, Headphones, Home, Leaf, MapPin, MessageCircle, Paintbrush, Search, ShieldCheck, Snowflake, Wrench, Zap } from "lucide-react";
import { MobileMenu } from "./components/mobile-menu";
import { siteConfig } from "../lib/site-config";

const categories = [
  { name: "Automotor", icon: Car }, { name: "Electricidad", icon: Zap }, { name: "Refrigeración", icon: Snowflake }, { name: "Jardinería", icon: Leaf },
  { name: "Chapería y pintura", icon: Paintbrush }, { name: "Hogar", icon: Home }, { name: "Reparaciones", icon: Wrench }, { name: "Construcción", icon: Hammer },
];
const services = [
  { title: "Electricidad automotriz", text: "Diagnóstico y reparación eléctrica.", image: "https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=900&q=82", type: "Atención rápida" },
  { title: "Aire acondicionado", text: "Instalación · reparación · mantenimiento", image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=82", type: "Servicio destacado" },
  { title: "Jardinería y mantenimiento", text: "Evaluamos el trabajo y preparamos tu cotización.", image: "https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=900&q=82", type: "Con evaluación" },
  { title: "Electricidad para el hogar", text: "Instalaciones, fallas y mantenimiento.", image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=82", type: "Atención rápida" },
  { title: "Chapería y pintura", text: "Evaluación y cotización según tu vehículo.", image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=900&q=82", type: "Con evaluación" },
  { title: "Reparaciones generales", text: "Contanos el problema y gestionamos la solución.", image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=82", type: "Atención rápida" },
];
const focus = "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-500";
const Logo = () => <span className="flex items-center gap-2.5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-brand-500 text-ink"><Wrench size={18} strokeWidth={2}/></span><span className="whitespace-nowrap text-[15px] font-semibold tracking-[-.03em] min-[390px]:text-base sm:text-lg">TODOSERVICIOS <span className="text-brand-600">PY</span></span></span>;

export default function HomePage() {
 return <main className="min-h-screen bg-[#f3f5f2] pb-20 sm:pb-0">
  <header className="sticky top-0 z-40 border-b border-white/10 bg-ink text-white shadow-sm">
   <div className="container-shell flex h-16 items-center justify-between gap-3 sm:h-[68px]">
    <a href="#inicio" aria-label={`${siteConfig.brandName} - Inicio`} className={focus}><Logo/></a>
    <nav className="hidden items-center gap-7 text-[13px] text-white/75 lg:flex" aria-label="Navegación principal"><a href="#categorias">Categorías</a><a href="#servicios">Servicios</a><a href="#como-funciona">Cómo funciona</a><a href="#prestadores">Prestadores</a></nav>
    <div className="hidden items-center gap-3 sm:flex"><a href="#servicios" className="px-3 py-2 text-[13px] text-white/75">Ver servicios</a><a href="#solicitud" className="rounded-lg bg-brand-500 px-5 py-2.5 text-[13px] font-semibold text-ink">Solicitar atención</a></div><MobileMenu/>
   </div>
  </header>

  <section id="inicio" className="border-b border-black/[.06] bg-ink text-white">
   <div className="container-shell grid gap-6 py-7 sm:py-9 lg:grid-cols-[1.15fr_.85fr] lg:gap-8 lg:py-10">
    <div>
     <div className="mb-4 flex items-center gap-2 text-[12px] text-white/65"><Headphones size={15} className="text-brand-400"/> Central integral de servicios</div>
     <h1 className="max-w-3xl text-[32px] font-normal leading-[1.08] tracking-[-.04em] min-[390px]:text-[35px] sm:text-[46px] lg:text-[52px]">Todos los servicios que necesitás, <span className="text-brand-400">en un solo lugar.</span></h1>
     <p className="mt-3 max-w-2xl text-[14px] leading-6 text-white/65 sm:text-[15px]">Contanos qué necesitás. Atendemos, evaluamos, cotizamos y coordinamos la solución.</p>
     <form id="solicitud" action="#atencion-central" className="mt-6 grid gap-2 rounded-xl bg-white p-2 text-ink shadow-[0_10px_30px_rgba(0,0,0,.16)] sm:grid-cols-[1fr_190px_auto]">
      <label className="flex min-h-[52px] items-center gap-3 px-3"><span className="sr-only">¿Qué necesitás resolver?</span><Search size={18} className="shrink-0 text-black/40"/><input name="necesidad" placeholder="¿Qué necesitás resolver?" className={`min-w-0 flex-1 bg-transparent text-[14px] outline-none placeholder:text-black/45 ${focus}`}/></label>
      <label className="flex min-h-[52px] items-center gap-2 border-t border-black/[.07] px-3 sm:border-l sm:border-t-0"><span className="sr-only">Tu ciudad o ubicación</span><MapPin size={17} className="shrink-0 text-brand-600"/><select name="zona" defaultValue="" className={`w-full bg-transparent text-[14px] outline-none ${focus}`}><option value="" disabled>Tu ubicación</option><option>Asunción</option><option>Central</option><option>San Lorenzo</option><option>Luque</option><option>Otra ciudad</option></select></label>
      <button className={`min-h-[52px] rounded-lg bg-brand-500 px-6 text-[14px] font-semibold transition hover:bg-brand-400 active:scale-[.99] ${focus}`}>Solicitar atención</button>
     </form>
     <div className="mt-5"><p className="mb-3 text-[11px] uppercase tracking-[.12em] text-white/45">Accesos rápidos</p><div className="flex flex-wrap gap-2">{categories.slice(0,6).map(({name})=><a key={name} href="#solicitud" className="rounded-full border border-white/15 bg-white/[.06] px-3 py-2 text-[12px] text-white/80 transition hover:border-brand-400 hover:text-white">{name}</a>)}<a href="#categorias" className="rounded-full bg-brand-500 px-3 py-2 text-[12px] font-medium text-ink">Más servicios</a></div></div>
    </div>
    <aside className="hidden lg:grid lg:grid-rows-[1fr_auto] lg:gap-3">
     <div className="relative min-h-[280px] overflow-hidden rounded-xl"><img src="https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=1000&q=84" alt="Profesional realizando un servicio" width="1000" height="700" className="h-full w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-5 pt-16"><p className="mb-0 text-[13px] text-white/85">Una sola atención para distintas necesidades.</p></div></div>
     <a href="#atencion-central" className="flex items-center justify-between rounded-xl bg-white p-4 text-ink"><span className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[#fff2b8]"><MessageCircle size={19}/></span><span><strong className="block text-[13px] font-semibold">Atención central</strong><span className="text-[12px] text-black/55">Un número. Una atención. Todos los servicios.</span></span></span><ArrowRight size={17}/></a>
    </aside>
   </div>
  </section>

  <section className="border-b border-black/[.06] bg-white py-4"><div className="container-shell grid gap-2 sm:grid-cols-3"><span className="flex items-center gap-2 text-[13px]"><Headphones size={16} className="text-brand-600"/> Atención centralizada</span><span className="flex items-center gap-2 text-[13px]"><ClipboardCheck size={16} className="text-brand-600"/> Cotización clara</span><span className="flex items-center gap-2 text-[13px]"><BadgeCheck size={16} className="text-brand-600"/> Coordinación del servicio</span></div></section>

  <section id="categorias" className="scroll-mt-20 py-7 sm:py-9"><div className="container-shell">
   <div className="mb-4 flex items-end justify-between"><div><p className="mb-1 text-[11px] font-semibold uppercase tracking-[.12em] text-brand-600">Acceso rápido</p><h2 className="text-[23px] font-normal tracking-[-.025em] sm:text-[28px]">¿Qué necesitás resolver?</h2></div><a href="#servicios" className="hidden text-[13px] sm:block">Ver todos →</a></div>
   <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-8">{categories.map(({name,icon:Icon})=><a key={name} href="#solicitud" className={`group flex min-h-[88px] items-center gap-3 rounded-lg border border-black/[.08] bg-white p-3 transition hover:border-brand-500 hover:bg-[#fffdf4] sm:flex-col sm:justify-center sm:text-center ${focus}`}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#f2f4ef] group-hover:bg-[#fff0b8]"><Icon size={19} strokeWidth={1.7}/></span><span className="text-[13px] font-medium leading-tight">{name}</span></a>)}</div>
  </div></section>

  <section className="pb-7 sm:pb-9"><div className="container-shell grid gap-3 md:grid-cols-2">
   <a href="#solicitud" className="group flex min-h-[150px] flex-col justify-between rounded-xl bg-ink p-5 text-white sm:p-6"><div><p className="mb-2 text-[11px] uppercase tracking-[.12em] text-brand-400">Necesito ayuda ahora</p><h2 className="text-[22px] font-normal">¿Necesitás resolver algo hoy?</h2><p className="mt-2 text-[13px] leading-5 text-white/60">Contanos el problema y gestionamos la atención.</p></div><span className="mt-4 inline-flex items-center gap-2 text-[13px] font-medium">Solicitar atención <ArrowRight size={16}/></span></a>
   <a href="#solicitud" className="group flex min-h-[150px] flex-col justify-between rounded-xl border border-[#e1b32d] bg-[#fff1b8] p-5 text-ink sm:p-6"><div><p className="mb-2 text-[11px] uppercase tracking-[.12em] text-[#805d00]">Trabajo con evaluación</p><h2 className="text-[22px] font-normal">¿Necesitás cotizar un trabajo?</h2><p className="mt-2 text-[13px] leading-5 text-black/60">Describí lo que necesitás y preparamos la evaluación.</p></div><span className="mt-4 inline-flex items-center gap-2 text-[13px] font-medium">Pedir cotización <ArrowRight size={16}/></span></a>
  </div></section>

  <section id="servicios" className="scroll-mt-20 bg-white py-8 sm:py-10"><div className="container-shell"><div className="mb-5"><p className="mb-1 text-[11px] font-semibold uppercase tracking-[.12em] text-brand-600">Servicios frecuentes</p><h2 className="text-[23px] font-normal tracking-[-.025em] sm:text-[28px]">Soluciones que podés solicitar ahora</h2></div>
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{services.map((service,i)=><a key={service.title} href="#solicitud" className={`group grid overflow-hidden rounded-xl border border-black/[.08] bg-white transition hover:border-black/20 ${i<2?"md:grid-cols-[130px_1fr] lg:grid-cols-1":""}`}><div className={`${i<2?"aspect-[4/3] md:aspect-auto lg:aspect-[3/2]":"aspect-[4/3]"} overflow-hidden bg-black/[.03]`}><img loading="lazy" width="900" height="650" src={service.image} alt={service.title} className="h-full w-full object-cover transition duration-200 group-hover:scale-[1.02]"/></div><div className="flex flex-col p-4"><span className="text-[10px] font-medium uppercase tracking-[.08em] text-brand-600">{service.type}</span><h3 className="mt-2 text-[16px] font-semibold">{service.title}</h3><p className="mt-1 text-[13px] leading-5 text-black/60">{service.text}</p><span className="mt-4 inline-flex items-center gap-1.5 text-[13px] font-medium">Solicitar <ArrowRight size={15}/></span></div></a>)}</div>
  </div></section>

  <section id="como-funciona" className="scroll-mt-20 py-8 sm:py-10"><div className="container-shell grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-1 text-[11px] font-semibold uppercase tracking-[.12em] text-brand-600">Cómo funciona</p><h2 className="max-w-md text-[24px] font-normal tracking-[-.025em] sm:text-[29px]">Vos contás la necesidad. Nosotros gestionamos la solución.</h2></div><div className="grid gap-2 sm:grid-cols-3">{[["01","Contanos qué necesitás"],["02","Recibí atención y cotización"],["03","Coordinamos el servicio"]].map(([n,t])=><div key={n} className="border-l-2 border-brand-500 bg-white p-4"><span className="text-[11px] font-semibold text-brand-600">{n}</span><h3 className="mt-2 text-[14px] font-semibold leading-snug">{t}</h3></div>)}</div></div></section>

  <section id="atencion-central" className="scroll-mt-20 pb-8 sm:pb-10"><div className="container-shell grid overflow-hidden rounded-xl bg-ink text-white lg:grid-cols-[1fr_auto]"><div className="p-6 sm:p-8"><div className="flex items-center gap-2 text-[11px] uppercase tracking-[.12em] text-brand-400"><MessageCircle size={16}/> Atención central TodosServicios PY</div><h2 className="mt-3 text-[25px] font-normal tracking-tight sm:text-[30px]">Un número. Una atención. Todos los servicios.</h2><p className="mt-2 max-w-2xl text-[14px] leading-6 text-white/65">Centralizamos la atención, cotización y coordinación de tus servicios desde un solo lugar.</p></div><div className="flex items-center border-t border-white/10 p-6 lg:border-l lg:border-t-0"><a href="#solicitud" className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-brand-500 px-6 text-[13px] font-semibold text-ink">Solicitar atención <ArrowRight size={16}/></a></div></div></section>

  <section className="bg-white py-8"><div className="container-shell grid gap-4 lg:grid-cols-[1fr_1.3fr]"><div><p className="mb-1 text-[11px] font-semibold uppercase tracking-[.12em] text-brand-600">Confianza operativa</p><h2 className="text-[23px] font-normal">Un solo contacto. Múltiples soluciones.</h2></div><div className="grid gap-3 sm:grid-cols-3">{[[Headphones,"Atención centralizada"],[ClipboardCheck,"Cotización clara"],[ShieldCheck,"Coordinación"]].map(([Icon,title])=>{const C=Icon as typeof Headphones; return <div key={String(title)} className="flex gap-3"><C size={19} className="mt-0.5 shrink-0 text-brand-600"/><div><h3 className="text-[14px] font-semibold">{String(title)}</h3><p className="mt-1 text-[12px] leading-5 text-black/55">Un proceso simple para resolver tu necesidad.</p></div></div>})}</div></div></section>

  <section id="prestadores" className="scroll-mt-20 py-7"><div className="container-shell flex flex-col gap-4 border-b border-black/[.08] pb-7 sm:flex-row sm:items-center sm:justify-between"><div><p className="mb-1 text-[11px] uppercase tracking-[.12em] text-black/45">Red de prestadores</p><h2 className="text-[20px] font-normal">¿Sos profesional o tenés una empresa de servicios?</h2></div><a href="#atencion-central" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-ink px-5 text-[13px] font-medium">Quiero trabajar con {siteConfig.brandName} <ArrowRight size={15}/></a></div></section>

  <footer className="bg-[#f3f5f2] py-7"><div className="container-shell grid gap-6 sm:grid-cols-3"><div><Logo/><p className="mt-3 text-[13px] text-black/55">Central integral de servicios para Paraguay.</p></div><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.1em] text-black/45">Navegación</p><div className="flex flex-wrap gap-x-4 gap-y-2 text-[13px] text-black/60"><a href="#categorias">Categorías</a><a href="#servicios">Servicios</a><a href="#como-funciona">Cómo funciona</a></div></div><div className="text-[12px] text-black/45 sm:text-right">© 2026 {siteConfig.brandName}</div></div></footer>
  <a href="#solicitud" className={`fixed left-3 right-3 z-30 flex min-h-12 items-center justify-center gap-2 rounded-lg bg-brand-500 px-5 text-[13px] font-semibold text-ink shadow-[0_8px_22px_rgba(0,0,0,.18)] [bottom:calc(.75rem+env(safe-area-inset-bottom))] sm:hidden ${focus}`}>Solicitar atención <ArrowRight size={16}/></a>
 </main>;
}
