-- Generated from data/services.ts and lib/site-config.ts. Do not hand-edit.
-- Regenerate with: node --experimental-strip-types scripts/generate-cms-seed-migration.mjs

begin;

insert into public.categories (name, slug, icon, active, featured, show_on_home, sort_order) values
  ('Hogar y mantenimiento', 'hogar-mantenimiento', 'House', true, true, true, 1),
  ('Climatización y refrigeración', 'climatizacion-refrigeracion', 'Snowflake', true, true, true, 2),
  ('Automotor', 'automotor', 'Car', true, true, true, 3),
  ('Construcción y remodelación', 'construccion-remodelacion', 'HardHat', true, true, true, 4),
  ('Jardín y exteriores', 'jardin-exteriores', 'Leaf', true, true, true, 5),
  ('Limpieza', 'limpieza', 'Sparkles', true, true, true, 6),
  ('Seguridad', 'seguridad', 'ShieldCheck', true, true, true, 7),
  ('Carpintería, herrería y aberturas', 'carpinteria-herreria-aberturas', 'Hammer', true, true, true, 8),
  ('Electrodomésticos', 'electrodomesticos', 'WashingMachine', true, false, false, 9),
  ('Tecnología', 'tecnologia', 'Laptop', true, false, false, 10),
  ('Mudanzas y logística', 'mudanzas-logistica', 'Truck', true, false, false, 11),
  ('Control de plagas', 'control-plagas', 'Bug', true, false, false, 12),
  ('Empresas y comercios', 'empresas-comercios', 'Building2', true, false, false, 13)
on conflict (slug) do update set
  name = excluded.name, icon = excluded.icon, active = excluded.active, featured = excluded.featured,
  show_on_home = excluded.show_on_home, sort_order = excluded.sort_order;

insert into public.services (name, slug, short_description, service_type, image_url, active, featured, show_on_home, sort_order, keywords) values
  ('Electricidad', 'electricidad', 'Instalaciones, reparaciones y mantenimiento eléctrico.', 'quick', null, true, true, true, 1, '{"luz","enchufe","llave","cable","cortocircuito","tablero","electricista"}'::text[]),
  ('Plomería', 'plomeria', 'Pérdidas, cañerías, sanitarios e instalaciones.', 'quick', null, true, true, true, 2, '{"canilla","cañeria","cañería","perdida","pérdida","agua","sanitario","baño"}'::text[]),
  ('Reparaciones generales', 'reparaciones-generales', 'Arreglos y mantenimiento cotidiano del hogar.', 'quick', null, true, false, false, 3, '{"arreglo","reparacion","reparación","mantenimiento"}'::text[]),
  ('Albañilería', 'albanileria', 'Reparaciones, muros y trabajos de albañilería.', 'evaluation', null, true, false, false, 4, '{"albañil","muro","pared","revoque"}'::text[]),
  ('Pintura', 'pintura', 'Interior, exterior y trabajos de terminación.', 'evaluation', null, true, false, false, 5, '{"pintor","pared","interior","exterior","terminacion","terminación"}'::text[]),
  ('Impermeabilización', 'impermeabilizacion', 'Soluciones para humedad, filtraciones y superficies.', 'evaluation', null, true, false, false, 6, '{"humedad","filtracion","filtración","gotera","techo"}'::text[]),
  ('Techos y goteras', 'techos-goteras', 'Evaluación y reparación de filtraciones y cubiertas.', 'evaluation', null, true, false, false, 7, '{"gotera","techo","lluvia","filtracion","filtración"}'::text[]),
  ('Instalaciones', 'instalaciones-hogar', 'Montajes e instalaciones para el hogar.', 'evaluation', null, false, false, false, 100, '{"instalar","montaje","colocar"}'::text[]),
  ('Mantenimiento del hogar', 'mantenimiento-hogar', 'Mantenimiento general y preventivo.', 'evaluation', null, false, false, false, 100, '{"mantenimiento","casa","hogar"}'::text[]),
  ('Instalación de aire acondicionado', 'instalacion-aire-acondicionado', 'Instalación y puesta en marcha de equipos.', 'specialized', null, true, true, true, 10, '{"aire","ac","split","instalacion","instalación"}'::text[]),
  ('Mantenimiento de aire acondicionado', 'mantenimiento-aire-acondicionado', 'Limpieza y mantenimiento preventivo de equipos.', 'specialized', null, true, false, false, 11, '{"aire","split","limpieza","mantenimiento"}'::text[]),
  ('Reparación de aire acondicionado', 'reparacion-aire-acondicionado', 'Diagnóstico y reparación de equipos de climatización.', 'specialized', null, true, false, false, 12, '{"aire","split","no enfria","no enfría","reparacion","reparación"}'::text[]),
  ('Refrigeración comercial', 'refrigeracion-comercial', 'Evaluación y mantenimiento de sistemas comerciales.', 'specialized', null, false, false, false, 100, '{"refrigeracion","refrigeración","comercial","frio","frío"}'::text[]),
  ('Heladeras y freezers', 'heladeras-freezers', 'Diagnóstico y reparación de equipos de frío.', 'specialized', null, false, false, false, 100, '{"heladera","freezer","frio","frío"}'::text[]),
  ('Cámaras frigoríficas', 'camaras-frigorificas', 'Servicio técnico para sistemas de frío industrial.', 'specialized', null, false, false, false, 100, '{"camara frigorifica","cámara frigorífica","frigorifico","frigorífico"}'::text[]),
  ('Electricidad automotriz', 'electricidad-automotriz', 'Diagnóstico y soluciones eléctricas para vehículos.', 'specialized', null, true, true, true, 20, '{"auto","vehiculo","vehículo","electricidad","arranque","alternador"}'::text[]),
  ('Mecánica', 'mecanica', 'Diagnóstico, reparación y mantenimiento mecánico.', 'specialized', null, true, false, false, 21, '{"mecanico","mecánico","motor","auto","vehiculo","vehículo"}'::text[]),
  ('Chapería', 'chaperia', 'Evaluación de golpes y reparación de carrocería.', 'evaluation', null, true, false, false, 100, '{"chapa","choque","golpe","carroceria","carrocería"}'::text[]),
  ('Pintura automotriz', 'pintura-automotriz', 'Pintura y terminación de carrocería.', 'evaluation', null, true, false, false, 100, '{"pintura auto","rayon","rayón","carroceria","carrocería"}'::text[]),
  ('Diagnóstico automotor', 'diagnostico-automotor', 'Evaluación técnica para identificar fallas.', 'specialized', null, false, false, false, 100, '{"scanner","diagnostico","diagnóstico","falla"}'::text[]),
  ('Auxilio mecánico', 'auxilio-mecanico', 'Asistencia mecánica según ubicación y necesidad.', 'specialized', null, false, false, false, 100, '{"auxilio","quedado","ruta","auto"}'::text[]),
  ('Baterías', 'baterias', 'Evaluación de batería y sistema de carga.', 'specialized', null, false, false, false, 100, '{"bateria","batería","arranque"}'::text[]),
  ('Aire acondicionado automotor', 'aire-acondicionado-automotor', 'Diagnóstico y servicio de climatización vehicular.', 'specialized', null, false, false, false, 100, '{"aire auto","ac auto","climatizacion auto"}'::text[]),
  ('Construcción', 'construccion', 'Trabajos de construcción según alcance y proyecto.', 'evaluation', null, true, true, true, 30, '{"obra","construir","construccion","construcción"}'::text[]),
  ('Remodelaciones', 'remodelaciones', 'Reformas y mejoras de espacios existentes.', 'evaluation', null, true, false, false, 100, '{"remodelar","reforma","renovacion","renovación"}'::text[]),
  ('Pisos', 'pisos', 'Colocación y reparación de pisos.', 'evaluation', null, false, false, false, 100, '{"piso","ceramica","cerámica","porcelanato"}'::text[]),
  ('Revestimientos', 'revestimientos', 'Colocación de revestimientos interiores y exteriores.', 'evaluation', null, false, false, false, 100, '{"revestimiento","azulejo"}'::text[]),
  ('Cielorrasos', 'cielorrasos', 'Instalación y reparación de cielorrasos.', 'evaluation', null, false, false, false, 100, '{"cielorraso","techo interior"}'::text[]),
  ('Durlock / yeso', 'durlock-yeso', 'Divisiones, cielorrasos y terminaciones en seco.', 'evaluation', null, false, false, false, 100, '{"durlock","yeso","placa"}'::text[]),
  ('Jardinería', 'jardineria', 'Cuidado y puesta a punto de espacios verdes.', 'evaluation', null, true, true, true, 40, '{"jardin","jardín","plantas","patio"}'::text[]),
  ('Mantenimiento de jardines', 'mantenimiento-jardines', 'Mantenimiento periódico de jardines y exteriores.', 'evaluation', null, true, false, false, 100, '{"jardinero","jardín","mantenimiento"}'::text[]),
  ('Poda', 'poda', 'Poda y mantenimiento de árboles y plantas.', 'evaluation', null, true, false, false, 100, '{"arbol","árbol","rama","podar"}'::text[]),
  ('Limpieza de terrenos', 'limpieza-terrenos', 'Desmalezado y limpieza general de terrenos.', 'evaluation', null, false, false, false, 100, '{"terreno","desmalezar","maleza"}'::text[]),
  ('Césped', 'cesped', 'Colocación y mantenimiento de césped.', 'evaluation', null, false, false, false, 100, '{"cesped","césped","pasto"}'::text[]),
  ('Riego', 'riego', 'Instalación y mantenimiento de sistemas de riego.', 'specialized', null, false, false, false, 100, '{"riego","aspersor","agua"}'::text[]),
  ('Paisajismo', 'paisajismo', 'Diseño y mejora de espacios exteriores.', 'evaluation', null, false, false, false, 100, '{"paisajismo","jardin","jardín","diseño"}'::text[]),
  ('Mantenimiento de piscinas', 'mantenimiento-piscinas', 'Limpieza y mantenimiento general de piscinas.', 'specialized', null, false, false, false, 100, '{"piscina","pileta","agua"}'::text[]),
  ('Limpieza residencial', 'limpieza-residencial', 'Limpieza general de casas y departamentos.', 'quick', null, true, true, true, 50, '{"limpieza","casa","departamento"}'::text[]),
  ('Limpieza de oficinas', 'limpieza-oficinas', 'Servicio de limpieza para espacios de trabajo.', 'evaluation', null, false, false, false, 100, '{"oficina","empresa","limpieza"}'::text[]),
  ('Limpieza profunda', 'limpieza-profunda', 'Limpieza intensiva de ambientes y superficies.', 'evaluation', null, true, false, false, 100, '{"profunda","limpieza general"}'::text[]),
  ('Limpieza post obra', 'limpieza-post-obra', 'Limpieza final después de obras y remodelaciones.', 'evaluation', null, false, false, false, 100, '{"post obra","obra","polvo"}'::text[]),
  ('Limpieza de vidrios', 'limpieza-vidrios', 'Limpieza de vidrios y superficies acristaladas.', 'evaluation', null, false, false, false, 100, '{"vidrio","ventana","cristal"}'::text[]),
  ('Limpieza de tapizados', 'limpieza-tapizados', 'Limpieza de sofás, sillas y tapizados.', 'evaluation', null, false, false, false, 100, '{"sofa","sofá","sillon","sillón","tapizado"}'::text[]),
  ('Lavado de alfombras', 'lavado-alfombras', 'Lavado y limpieza profunda de alfombras.', 'evaluation', null, false, false, false, 100, '{"alfombra","lavado"}'::text[]),
  ('Cámaras de seguridad', 'camaras-seguridad', 'Instalación y configuración de videovigilancia.', 'specialized', null, true, true, true, 60, '{"camara","cámara","cctv","vigilancia","camara ip","cámara ip"}'::text[]),
  ('Alarmas', 'alarmas', 'Instalación y configuración de sistemas de alarma.', 'specialized', null, false, false, false, 100, '{"alarma","sensor","seguridad"}'::text[]),
  ('Cercos eléctricos', 'cercos-electricos', 'Instalación y mantenimiento de cercos eléctricos.', 'specialized', null, false, false, false, 100, '{"cerco","electrico","eléctrico","perimetral"}'::text[]),
  ('Porteros eléctricos', 'porteros-electricos', 'Instalación y reparación de porteros eléctricos.', 'specialized', null, false, false, false, 100, '{"portero","timbre","intercomunicador"}'::text[]),
  ('Videoporteros', 'videoporteros', 'Instalación y configuración de videoporteros.', 'specialized', null, false, false, false, 100, '{"videoportero","portero","camara puerta"}'::text[]),
  ('Control de acceso', 'control-acceso', 'Soluciones de acceso para hogares y empresas.', 'specialized', null, false, false, false, 100, '{"acceso","tarjeta","biometrico","biométrico"}'::text[]),
  ('Cerraduras', 'cerraduras', 'Instalación, cambio y reparación de cerraduras.', 'quick', null, false, false, false, 100, '{"cerradura","llave","puerta"}'::text[]),
  ('Carpintería', 'carpinteria', 'Reparaciones y trabajos de carpintería.', 'evaluation', null, false, false, false, 100, '{"carpintero","madera","puerta"}'::text[]),
  ('Muebles a medida', 'muebles-medida', 'Diseño y fabricación según espacio y necesidad.', 'evaluation', null, false, false, false, 100, '{"mueble","placard","estante"}'::text[]),
  ('Herrería', 'herreria', 'Trabajos, reparaciones y estructuras metálicas.', 'evaluation', null, true, true, true, 70, '{"herrero","metal","hierro","porton","portón"}'::text[]),
  ('Soldadura', 'soldadura', 'Trabajos y reparaciones mediante soldadura.', 'evaluation', null, false, false, false, 100, '{"soldar","soldadura","metal"}'::text[]),
  ('Portones', 'portones', 'Fabricación, reparación y mantenimiento de portones.', 'evaluation', null, false, false, false, 100, '{"porton","portón","entrada"}'::text[]),
  ('Automatización de portones', 'automatizacion-portones', 'Motores, controles y automatización de accesos.', 'specialized', null, false, false, false, 100, '{"porton","portón","motor","control remoto","automatizacion"}'::text[]),
  ('Vidriería', 'vidrieria', 'Reposición e instalación de vidrios.', 'evaluation', null, false, false, false, 100, '{"vidrio","cristal","ventana"}'::text[]),
  ('Aluminio', 'aluminio', 'Trabajos en perfiles y estructuras de aluminio.', 'evaluation', null, false, false, false, 100, '{"aluminio","perfil"}'::text[]),
  ('Aberturas', 'aberturas', 'Instalación y reparación de puertas y ventanas.', 'evaluation', null, false, false, false, 100, '{"abertura","puerta","ventana"}'::text[]),
  ('Reparación de lavarropas', 'reparacion-lavarropas', 'Diagnóstico y reparación de lavarropas.', 'specialized', null, true, true, true, 80, '{"lavarropas","lavadora","centrifuga","centrífuga"}'::text[]),
  ('Hornos', 'hornos', 'Diagnóstico y reparación de hornos.', 'specialized', null, false, false, false, 100, '{"horno","calor"}'::text[]),
  ('Cocinas', 'cocinas', 'Diagnóstico y reparación de cocinas.', 'specialized', null, false, false, false, 100, '{"cocina","hornalla"}'::text[]),
  ('Microondas', 'microondas', 'Diagnóstico y reparación de microondas.', 'specialized', null, false, false, false, 100, '{"microondas"}'::text[]),
  ('Secarropas', 'secarropas', 'Diagnóstico y reparación de secarropas.', 'specialized', null, false, false, false, 100, '{"secarropas","secadora"}'::text[]),
  ('Pequeños electrodomésticos', 'pequenos-electrodomesticos', 'Evaluación de pequeños equipos del hogar.', 'specialized', null, false, false, false, 100, '{"electrodomestico","electrodoméstico","aparato"}'::text[]),
  ('Instalación de Wi-Fi', 'wifi', 'Configuración y mejora de cobertura Wi-Fi.', 'specialized', null, true, true, true, 90, '{"wifi","internet","router","señal"}'::text[]),
  ('Redes', 'redes', 'Instalación y configuración de redes.', 'specialized', null, false, false, false, 100, '{"red","cableado","ethernet","internet"}'::text[]),
  ('Computadoras', 'computadoras', 'Diagnóstico y soporte para computadoras.', 'specialized', null, true, false, false, 100, '{"pc","computadora","desktop"}'::text[]),
  ('Notebooks', 'notebooks', 'Diagnóstico y soporte para notebooks.', 'specialized', null, true, false, false, 100, '{"notebook","laptop","computadora"}'::text[]),
  ('Impresoras', 'impresoras', 'Configuración y diagnóstico de impresoras.', 'specialized', null, false, false, false, 100, '{"impresora","imprimir"}'::text[]),
  ('Configuración de dispositivos', 'configuracion-dispositivos', 'Configuración de equipos y dispositivos conectados.', 'specialized', null, false, false, false, 100, '{"configurar","dispositivo","equipo"}'::text[]),
  ('Soporte técnico', 'soporte-tecnico', 'Asistencia técnica para equipos y conectividad.', 'specialized', null, false, false, false, 100, '{"soporte","tecnico","técnico","ayuda"}'::text[]),
  ('Mudanzas', 'mudanzas', 'Traslado coordinado de muebles y pertenencias.', 'evaluation', null, false, false, false, 100, '{"mudanza","casa","traslado"}'::text[]),
  ('Fletes', 'fletes', 'Traslado de objetos y cargas según necesidad.', 'evaluation', null, false, false, false, 100, '{"flete","camion","camión","transporte"}'::text[]),
  ('Transporte de muebles', 'transporte-muebles', 'Traslado puntual de muebles y objetos grandes.', 'evaluation', null, false, false, false, 100, '{"mueble","traslado","transporte"}'::text[]),
  ('Retiro de objetos', 'retiro-objetos', 'Retiro coordinado de objetos y elementos voluminosos.', 'evaluation', null, false, false, false, 100, '{"retirar","objeto","escombro"}'::text[]),
  ('Traslado de cargas pequeñas', 'cargas-pequenas', 'Transporte de cargas pequeñas y puntuales.', 'evaluation', null, false, false, false, 100, '{"carga","paquete","traslado"}'::text[]),
  ('Fumigación', 'fumigacion', 'Tratamiento y control profesional de plagas.', 'specialized', null, false, false, false, 100, '{"fumigar","fumigacion","fumigación","plaga"}'::text[]),
  ('Control de insectos', 'control-insectos', 'Tratamientos para insectos según el caso.', 'specialized', null, false, false, false, 100, '{"cucaracha","hormiga","mosquito","insecto"}'::text[]),
  ('Control de roedores', 'control-roedores', 'Evaluación y control de roedores.', 'specialized', null, false, false, false, 100, '{"rata","raton","ratón","roedor"}'::text[]),
  ('Desinfección', 'desinfeccion', 'Tratamientos de desinfección para espacios.', 'specialized', null, false, false, false, 100, '{"desinfectar","desinfeccion","desinfección"}'::text[]),
  ('Mantenimiento eléctrico para empresas', 'mantenimiento-electrico-empresas', 'Mantenimiento preventivo y correctivo de instalaciones.', 'specialized', null, false, false, false, 100, '{"empresa","comercio","electrico","eléctrico"}'::text[]),
  ('Mantenimiento edilicio', 'mantenimiento-edilicio', 'Coordinación de mantenimiento general para inmuebles.', 'evaluation', null, false, false, false, 100, '{"edificio","local","mantenimiento"}'::text[]),
  ('Mantenimiento preventivo', 'mantenimiento-preventivo', 'Planificación de mantenimiento para reducir incidencias.', 'evaluation', null, false, false, false, 100, '{"preventivo","empresa","mantenimiento"}'::text[])
on conflict (slug) do update set
  name = excluded.name, short_description = excluded.short_description, service_type = excluded.service_type,
  image_url = excluded.image_url, active = excluded.active, featured = excluded.featured,
  show_on_home = excluded.show_on_home, sort_order = excluded.sort_order, keywords = excluded.keywords;

insert into public.service_categories (service_id, category_id)
select services.id, categories.id
from (values
  ('electricidad', 'hogar-mantenimiento'),
  ('electricidad', 'empresas-comercios'),
  ('plomeria', 'hogar-mantenimiento'),
  ('reparaciones-generales', 'hogar-mantenimiento'),
  ('reparaciones-generales', 'empresas-comercios'),
  ('albanileria', 'hogar-mantenimiento'),
  ('albanileria', 'construccion-remodelacion'),
  ('pintura', 'hogar-mantenimiento'),
  ('pintura', 'construccion-remodelacion'),
  ('pintura', 'empresas-comercios'),
  ('impermeabilizacion', 'hogar-mantenimiento'),
  ('impermeabilizacion', 'construccion-remodelacion'),
  ('techos-goteras', 'hogar-mantenimiento'),
  ('techos-goteras', 'construccion-remodelacion'),
  ('instalaciones-hogar', 'hogar-mantenimiento'),
  ('mantenimiento-hogar', 'hogar-mantenimiento'),
  ('instalacion-aire-acondicionado', 'climatizacion-refrigeracion'),
  ('mantenimiento-aire-acondicionado', 'climatizacion-refrigeracion'),
  ('mantenimiento-aire-acondicionado', 'empresas-comercios'),
  ('reparacion-aire-acondicionado', 'climatizacion-refrigeracion'),
  ('refrigeracion-comercial', 'climatizacion-refrigeracion'),
  ('refrigeracion-comercial', 'empresas-comercios'),
  ('heladeras-freezers', 'climatizacion-refrigeracion'),
  ('heladeras-freezers', 'electrodomesticos'),
  ('camaras-frigorificas', 'climatizacion-refrigeracion'),
  ('camaras-frigorificas', 'empresas-comercios'),
  ('electricidad-automotriz', 'automotor'),
  ('mecanica', 'automotor'),
  ('chaperia', 'automotor'),
  ('pintura-automotriz', 'automotor'),
  ('diagnostico-automotor', 'automotor'),
  ('auxilio-mecanico', 'automotor'),
  ('baterias', 'automotor'),
  ('aire-acondicionado-automotor', 'automotor'),
  ('aire-acondicionado-automotor', 'climatizacion-refrigeracion'),
  ('construccion', 'construccion-remodelacion'),
  ('remodelaciones', 'construccion-remodelacion'),
  ('remodelaciones', 'hogar-mantenimiento'),
  ('pisos', 'construccion-remodelacion'),
  ('revestimientos', 'construccion-remodelacion'),
  ('cielorrasos', 'construccion-remodelacion'),
  ('durlock-yeso', 'construccion-remodelacion'),
  ('jardineria', 'jardin-exteriores'),
  ('mantenimiento-jardines', 'jardin-exteriores'),
  ('poda', 'jardin-exteriores'),
  ('limpieza-terrenos', 'jardin-exteriores'),
  ('limpieza-terrenos', 'limpieza'),
  ('cesped', 'jardin-exteriores'),
  ('riego', 'jardin-exteriores'),
  ('paisajismo', 'jardin-exteriores'),
  ('mantenimiento-piscinas', 'jardin-exteriores'),
  ('limpieza-residencial', 'limpieza'),
  ('limpieza-oficinas', 'limpieza'),
  ('limpieza-oficinas', 'empresas-comercios'),
  ('limpieza-profunda', 'limpieza'),
  ('limpieza-post-obra', 'limpieza'),
  ('limpieza-post-obra', 'construccion-remodelacion'),
  ('limpieza-vidrios', 'limpieza'),
  ('limpieza-tapizados', 'limpieza'),
  ('lavado-alfombras', 'limpieza'),
  ('camaras-seguridad', 'seguridad'),
  ('camaras-seguridad', 'tecnologia'),
  ('camaras-seguridad', 'empresas-comercios'),
  ('alarmas', 'seguridad'),
  ('cercos-electricos', 'seguridad'),
  ('porteros-electricos', 'seguridad'),
  ('videoporteros', 'seguridad'),
  ('control-acceso', 'seguridad'),
  ('control-acceso', 'empresas-comercios'),
  ('cerraduras', 'seguridad'),
  ('cerraduras', 'hogar-mantenimiento'),
  ('carpinteria', 'carpinteria-herreria-aberturas'),
  ('muebles-medida', 'carpinteria-herreria-aberturas'),
  ('herreria', 'carpinteria-herreria-aberturas'),
  ('soldadura', 'carpinteria-herreria-aberturas'),
  ('portones', 'carpinteria-herreria-aberturas'),
  ('portones', 'seguridad'),
  ('automatizacion-portones', 'carpinteria-herreria-aberturas'),
  ('automatizacion-portones', 'seguridad'),
  ('vidrieria', 'carpinteria-herreria-aberturas'),
  ('aluminio', 'carpinteria-herreria-aberturas'),
  ('aberturas', 'carpinteria-herreria-aberturas'),
  ('aberturas', 'hogar-mantenimiento'),
  ('reparacion-lavarropas', 'electrodomesticos'),
  ('hornos', 'electrodomesticos'),
  ('cocinas', 'electrodomesticos'),
  ('microondas', 'electrodomesticos'),
  ('secarropas', 'electrodomesticos'),
  ('pequenos-electrodomesticos', 'electrodomesticos'),
  ('wifi', 'tecnologia'),
  ('redes', 'tecnologia'),
  ('redes', 'empresas-comercios'),
  ('computadoras', 'tecnologia'),
  ('notebooks', 'tecnologia'),
  ('impresoras', 'tecnologia'),
  ('configuracion-dispositivos', 'tecnologia'),
  ('soporte-tecnico', 'tecnologia'),
  ('soporte-tecnico', 'empresas-comercios'),
  ('mudanzas', 'mudanzas-logistica'),
  ('fletes', 'mudanzas-logistica'),
  ('transporte-muebles', 'mudanzas-logistica'),
  ('retiro-objetos', 'mudanzas-logistica'),
  ('cargas-pequenas', 'mudanzas-logistica'),
  ('fumigacion', 'control-plagas'),
  ('control-insectos', 'control-plagas'),
  ('control-roedores', 'control-plagas'),
  ('desinfeccion', 'control-plagas'),
  ('desinfeccion', 'limpieza'),
  ('desinfeccion', 'empresas-comercios'),
  ('mantenimiento-electrico-empresas', 'empresas-comercios'),
  ('mantenimiento-edilicio', 'empresas-comercios'),
  ('mantenimiento-preventivo', 'empresas-comercios')
) as seed(service_slug, category_slug)
join public.services on services.slug = seed.service_slug
join public.categories on categories.slug = seed.category_slug
on conflict (service_id, category_id) do nothing;

insert into public.site_settings (key, value) values
  ('brandName', '"TodosServicios PY"'::jsonb),
  ('centralPhone', 'null'::jsonb),
  ('centralWhatsApp', 'null'::jsonb),
  ('serviceHours', 'null'::jsonb),
  ('centralAttentionLabel', '"Un número. Una atención. Todos los servicios."'::jsonb)
on conflict (key) do update set value = excluded.value;

commit;
